//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 03:03:52 PM MSK 
//


package com.baltinfo.radius.feed.cian.model;

import com.baltinfo.radius.feed.utils.DoubleExponentAdapter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Price" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="Currency" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="eur"/>
 *               &lt;enumeration value="rur"/>
 *               &lt;enumeration value="usd"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VatType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="included"/>
 *               &lt;enumeration value="notIncluded"/>
 *               &lt;enumeration value="vatIncluded"/>
 *               &lt;enumeration value="vatNotIncluded"/>
 *               &lt;enumeration value="usn"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VatPrice" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="ContractType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="leaseAssignment"/>
 *               &lt;enumeration value="sale"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AgentBonus" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *                   &lt;element name="PaymentType" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="percent"/>
 *                         &lt;enumeration value="fixed"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Currency" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="eur"/>
 *                         &lt;enumeration value="rur"/>
 *                         &lt;enumeration value="usd"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "price",
        "priceType",
        "currency",
        "vatType",
        "vatPrice",
        "contractType",
        "agentBonus",
        "paymentPeriod",
        "clientFee",
        "leaseTermType",
        "saleType"
})
public class BargainTerms {

    @XmlElement(name = "Price", type = String.class)
    @XmlJavaTypeAdapter(type = Double.class, value = DoubleExponentAdapter.class)
    @XmlSchemaType(name = "double")
    protected Double price;
    @XmlElement(name = "PriceType")
    protected String priceType;
    @XmlElement(name = "Currency", defaultValue = "rur")
    protected String currency;
    @XmlElement(name = "SaleType")
    protected String saleType;
    @XmlElement(name = "VatType")
    protected String vatType;
    @XmlElement(name = "VatPrice")
    protected Double vatPrice;
    @XmlElement(name = "ContractType")
    protected String contractType;
    @XmlElement(name = "AgentBonus")
    protected AgentBonus agentBonus;
    @XmlElement(name = "PaymentPeriod")
    protected String paymentPeriod;
    @XmlElement(name = "ClientFee")
    protected BigInteger clientFee;
    @XmlElement(name = "LeaseTermType")
    protected String leaseTermType;

    /**
     * Gets the value of the price property.
     */
    public Double getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     */
    public void setPrice(Double value) {
        this.price = value;
    }

    /**
     * Gets the value of the currency property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the vatType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVatType() {
        return vatType;
    }

    /**
     * Sets the value of the vatType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVatType(String value) {
        this.vatType = value;
    }
    /**
     * Gets the value of the saleType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSaleType() {
        return saleType;
    }

    /**
     * Sets the value of the saleType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSaleType(String value) {
        this.saleType = value;
    }
    /**
     * Gets the value of the vatPrice property.
     *
     * @return possible object is
     * {@link Double }
     */
    public Double getVatPrice() {
        return vatPrice;
    }

    /**
     * Sets the value of the vatPrice property.
     *
     * @param value allowed object is
     *              {@link Double }
     */
    public void setVatPrice(Double value) {
        this.vatPrice = value;
    }

    /**
     * Gets the value of the contractType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getContractType() {
        return contractType;
    }

    /**
     * Sets the value of the contractType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setContractType(String value) {
        this.contractType = value;
    }

    /**
     * Gets the value of the agentBonus property.
     *
     * @return possible object is
     * {@link AgentBonus }
     */
    public AgentBonus getAgentBonus() {
        return agentBonus;
    }

    /**
     * Sets the value of the agentBonus property.
     *
     * @param value allowed object is
     *              {@link AgentBonus }
     */
    public void setAgentBonus(AgentBonus value) {
        this.agentBonus = value;
    }

    public String getPaymentPeriod() {
        return paymentPeriod;
    }

    public void setPaymentPeriod(String paymentPeriod) {
        this.paymentPeriod = paymentPeriod;
    }

    public BigInteger getClientFee() {
        return clientFee;
    }

    public void setClientFee(BigInteger clientFee) {
        this.clientFee = clientFee;
    }

    public String getLeaseTermType() {
        return leaseTermType;
    }

    public void setLeaseTermType(String leaseTermType) {
        this.leaseTermType = leaseTermType;
    }

    public String getPriceType() {
        return priceType;
    }

    public void setPriceType(String priceType) {
        this.priceType = priceType;
    }
}
