//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 03:03:52 PM MSK 
//


package com.baltinfo.radius.feed.cian.model;

import com.baltinfo.radius.feed.utils.DoubleExponentAdapter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FloorsCount" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="BuildYear" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="MaterialType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="block"/>
 *               &lt;enumeration value="boards"/>
 *               &lt;enumeration value="brick"/>
 *               &lt;enumeration value="monolith"/>
 *               &lt;enumeration value="monolithBrick"/>
 *               &lt;enumeration value="old"/>
 *               &lt;enumeration value="panel"/>
 *               &lt;enumeration value="stalin"/>
 *               &lt;enumeration value="wood"/>
 *               &lt;enumeration value="wireframe"/>
 *               &lt;enumeration value="aerocreteBlock"/>
 *               &lt;enumeration value="gasSilicateBlock"/>
 *               &lt;enumeration value="foamConcreteBlock"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TotalArea" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="HeatingType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="autonomous"/>
 *               &lt;enumeration value="central"/>
 *               &lt;enumeration value="no"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CeilingHeight" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="Parking" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Type" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="ground"/>
 *                         &lt;enumeration value="multilevel"/>
 *                         &lt;enumeration value="roof"/>
 *                         &lt;enumeration value="underground"/>
 *                         &lt;enumeration value="open"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="PlacesCount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="PriceMonthly" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *                   &lt;element name="Currency" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="eur"/>
 *                         &lt;enumeration value="rur"/>
 *                         &lt;enumeration value="usd"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="IsFree" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Type" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="administrativeBuilding"/>
 *               &lt;enumeration value="businessCenter"/>
 *               &lt;enumeration value="businessCenter2"/>
 *               &lt;enumeration value="businessPark"/>
 *               &lt;enumeration value="businessQuarter"/>
 *               &lt;enumeration value="free"/>
 *               &lt;enumeration value="industrialComplex"/>
 *               &lt;enumeration value="industrialPark"/>
 *               &lt;enumeration value="industrialSite"/>
 *               &lt;enumeration value="industrialWarehouseComplex"/>
 *               &lt;enumeration value="logisticsCenter"/>
 *               &lt;enumeration value="logisticsComplex"/>
 *               &lt;enumeration value="mansion"/>
 *               &lt;enumeration value="manufactureBuilding"/>
 *               &lt;enumeration value="manufacturingFacility"/>
 *               &lt;enumeration value="modular"/>
 *               &lt;enumeration value="multifunctionalComplex"/>
 *               &lt;enumeration value="officeAndHotelComplex"/>
 *               &lt;enumeration value="officeAndResidentialComplex"/>
 *               &lt;enumeration value="officeAndWarehouse"/>
 *               &lt;enumeration value="officeAndWarehouseComplex"/>
 *               &lt;enumeration value="officeBuilding"/>
 *               &lt;enumeration value="officeIndustrialComplex"/>
 *               &lt;enumeration value="old"/>
 *               &lt;enumeration value="other"/>
 *               &lt;enumeration value="outlet"/>
 *               &lt;enumeration value="propertyComplex"/>
 *               &lt;enumeration value="residentialComplex"/>
 *               &lt;enumeration value="residentialHouse"/>
 *               &lt;enumeration value="shoppingAndBusinessComplex"/>
 *               &lt;enumeration value="shoppingAndCommunityCenter"/>
 *               &lt;enumeration value="shoppingAndEntertainmentCenter"/>
 *               &lt;enumeration value="shoppingCenter"/>
 *               &lt;enumeration value="specializedShoppingCenter"/>
 *               &lt;enumeration value="standaloneBuilding"/>
 *               &lt;enumeration value="technopark"/>
 *               &lt;enumeration value="tradingOfficeComplex"/>
 *               &lt;enumeration value="warehouse"/>
 *               &lt;enumeration value="warehouseComplex"/>
 *               &lt;enumeration value="officeQuarter"/>
 *               &lt;enumeration value="officeCenter"/>
 *               &lt;enumeration value="businessQuarter2"/>
 *               &lt;enumeration value="businessHouse"/>
 *               &lt;enumeration value="tradingHouse"/>
 *               &lt;enumeration value="officeComplex"/>
 *               &lt;enumeration value="tradeAndExhibitionComplex"/>
 *               &lt;enumeration value="shoppingComplex"/>
 *               &lt;enumeration value="shoppingAndWarehouseComplex"/>
 *               &lt;enumeration value="logisticsPark"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ClassType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="a"/>
 *               &lt;enumeration value="aPlus"/>
 *               &lt;enumeration value="b"/>
 *               &lt;enumeration value="bMinus"/>
 *               &lt;enumeration value="bPlus"/>
 *               &lt;enumeration value="c"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Developer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ManagementCompany" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VentilationType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="forced"/>
 *               &lt;enumeration value="natural"/>
 *               &lt;enumeration value="no"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ConditioningType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="central"/>
 *               &lt;enumeration value="local"/>
 *               &lt;enumeration value="no"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ExtinguishingSystemType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="alarm"/>
 *               &lt;enumeration value="gas"/>
 *               &lt;enumeration value="hydrant"/>
 *               &lt;enumeration value="no"/>
 *               &lt;enumeration value="powder"/>
 *               &lt;enumeration value="sprinkler"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ExtinguishingSystemTypes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ExtinguishingSystemTypeEnum" maxOccurs="unbounded">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="alarm"/>
 *                         &lt;enumeration value="gas"/>
 *                         &lt;enumeration value="hydrant"/>
 *                         &lt;enumeration value="no"/>
 *                         &lt;enumeration value="powder"/>
 *                         &lt;enumeration value="sprinkler"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="StatusType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="operational"/>
 *               &lt;enumeration value="project"/>
 *               &lt;enumeration value="underConstruction"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AccessType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="free"/>
 *               &lt;enumeration value="passSystem"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Infrastructure" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="HasCarWash" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="HasBuffet" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="HasCarService" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="HasCanteen" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="HasCentralReception" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="HasHotel" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="HasAtm" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="HasExhibitionAndWarehouseComplex" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="HasPharmacy" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="HasBankDepartment" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="HasCinema" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="HasCafe" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="HasMedicalCenter" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="HasBeautyShop" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="HasStudio" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="HasNotaryOffice" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="HasPool" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="HasClothesStudio" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="HasWarehouse" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="HasPark" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="HasRestaurant" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="HasFitnessCentre" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="HasSupermarket" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="HasMinimarket" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="HasShoppingArea" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="HasConferenceRoom" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "name",
        "floorsCount",
        "buildYear",
        "materialType",
        "totalArea",
        "heatingType",
        "ceilingHeight",
        "parking",
        "type",
        "classType",
        "developer",
        "managementCompany",
        "ventilationType",
        "conditioningType",
        "extinguishingSystemType",
        "extinguishingSystemTypes",
        "statusType",
        "accessType",
        "infrastructure"
})
public class Building {

    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "FloorsCount", required = true)
    protected BigInteger floorsCount;
    @XmlElement(name = "BuildYear")
    protected BigInteger buildYear;
    @XmlElement(name = "MaterialType")
    protected String materialType;
    @XmlElement(name = "TotalArea")
    @XmlJavaTypeAdapter(type = Double.class, value = DoubleExponentAdapter.class)
    protected Double totalArea;
    @XmlElement(name = "HeatingType")
    protected String heatingType;
    @XmlElement(name = "CeilingHeight")
    protected Double ceilingHeight;
    @XmlElement(name = "Parking")
    protected Parking parking;
    @XmlElement(name = "Type")
    protected String type;
    @XmlElement(name = "ClassType")
    protected String classType;
    @XmlElement(name = "Developer")
    protected String developer;
    @XmlElement(name = "ManagementCompany")
    protected String managementCompany;
    @XmlElement(name = "VentilationType")
    protected String ventilationType;
    @XmlElement(name = "ConditioningType")
    protected String conditioningType;
    @XmlElement(name = "ExtinguishingSystemType")
    protected String extinguishingSystemType;
    @XmlElement(name = "ExtinguishingSystemTypes")
    protected ExtinguishingSystemTypes extinguishingSystemTypes;
    @XmlElement(name = "StatusType")
    protected String statusType;
    @XmlElement(name = "AccessType")
    protected String accessType;
    @XmlElement(name = "Infrastructure")
    protected Infrastructure infrastructure;

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the floorsCount property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getFloorsCount() {
        return floorsCount;
    }

    /**
     * Sets the value of the floorsCount property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setFloorsCount(BigInteger value) {
        this.floorsCount = value;
    }

    /**
     * Gets the value of the buildYear property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getBuildYear() {
        return buildYear;
    }

    /**
     * Sets the value of the buildYear property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setBuildYear(BigInteger value) {
        this.buildYear = value;
    }

    /**
     * Gets the value of the materialType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMaterialType() {
        return materialType;
    }

    /**
     * Sets the value of the materialType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMaterialType(String value) {
        this.materialType = value;
    }

    /**
     * Gets the value of the totalArea property.
     */
    public Double getTotalArea() {
        return totalArea;
    }

    /**
     * Sets the value of the totalArea property.
     */
    public void setTotalArea(Double value) {
        this.totalArea = value;
    }

    /**
     * Gets the value of the heatingType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getHeatingType() {
        return heatingType;
    }

    /**
     * Sets the value of the heatingType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHeatingType(String value) {
        this.heatingType = value;
    }

    /**
     * Gets the value of the ceilingHeight property.
     *
     * @return possible object is
     * {@link Double }
     */
    public Double getCeilingHeight() {
        return ceilingHeight;
    }

    /**
     * Sets the value of the ceilingHeight property.
     *
     * @param value allowed object is
     *              {@link Double }
     */
    public void setCeilingHeight(Double value) {
        this.ceilingHeight = value;
    }

    /**
     * Gets the value of the parking property.
     *
     * @return possible object is
     * {@link Parking }
     */
    public Parking getParking() {
        return parking;
    }

    /**
     * Sets the value of the parking property.
     *
     * @param value allowed object is
     *              {@link Parking }
     */
    public void setParking(Parking value) {
        this.parking = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the classType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getClassType() {
        return classType;
    }

    /**
     * Sets the value of the classType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setClassType(String value) {
        this.classType = value;
    }

    /**
     * Gets the value of the developer property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDeveloper() {
        return developer;
    }

    /**
     * Sets the value of the developer property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDeveloper(String value) {
        this.developer = value;
    }

    /**
     * Gets the value of the managementCompany property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getManagementCompany() {
        return managementCompany;
    }

    /**
     * Sets the value of the managementCompany property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setManagementCompany(String value) {
        this.managementCompany = value;
    }

    /**
     * Gets the value of the ventilationType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVentilationType() {
        return ventilationType;
    }

    /**
     * Sets the value of the ventilationType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVentilationType(String value) {
        this.ventilationType = value;
    }

    /**
     * Gets the value of the conditioningType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getConditioningType() {
        return conditioningType;
    }

    /**
     * Sets the value of the conditioningType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setConditioningType(String value) {
        this.conditioningType = value;
    }

    /**
     * Gets the value of the extinguishingSystemType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getExtinguishingSystemType() {
        return extinguishingSystemType;
    }

    /**
     * Sets the value of the extinguishingSystemType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setExtinguishingSystemType(String value) {
        this.extinguishingSystemType = value;
    }

    /**
     * Gets the value of the extinguishingSystemTypes property.
     *
     * @return possible object is
     * {@link ExtinguishingSystemTypes }
     */
    public ExtinguishingSystemTypes getExtinguishingSystemTypes() {
        return extinguishingSystemTypes;
    }

    /**
     * Sets the value of the extinguishingSystemTypes property.
     *
     * @param value allowed object is
     *              {@link ExtinguishingSystemTypes }
     */
    public void setExtinguishingSystemTypes(ExtinguishingSystemTypes value) {
        this.extinguishingSystemTypes = value;
    }

    /**
     * Gets the value of the statusType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStatusType() {
        return statusType;
    }

    /**
     * Sets the value of the statusType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStatusType(String value) {
        this.statusType = value;
    }

    /**
     * Gets the value of the accessType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAccessType() {
        return accessType;
    }

    /**
     * Sets the value of the accessType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccessType(String value) {
        this.accessType = value;
    }

    /**
     * Gets the value of the infrastructure property.
     *
     * @return possible object is
     * {@link Infrastructure }
     */
    public Infrastructure getInfrastructure() {
        return infrastructure;
    }

    /**
     * Sets the value of the infrastructure property.
     *
     * @param value allowed object is
     *              {@link Infrastructure }
     */
    public void setInfrastructure(Infrastructure value) {
        this.infrastructure = value;
    }

}
