//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 03:03:52 PM MSK 
//


package com.baltinfo.radius.feed.cian.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HomeOwnerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HomeOwnerPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExactAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CadastralNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "homeOwnerName",
        "homeOwnerPhone",
        "exactAddress",
        "cadastralNumber"
})
public class ExtraData {

    @XmlElement(name = "HomeOwnerName")
    protected String homeOwnerName;
    @XmlElement(name = "HomeOwnerPhone")
    protected String homeOwnerPhone;
    @XmlElement(name = "ExactAddress")
    protected String exactAddress;
    @XmlElement(name = "CadastralNumber")
    protected String cadastralNumber;

    /**
     * Gets the value of the homeOwnerName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getHomeOwnerName() {
        return homeOwnerName;
    }

    /**
     * Sets the value of the homeOwnerName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHomeOwnerName(String value) {
        this.homeOwnerName = value;
    }

    /**
     * Gets the value of the homeOwnerPhone property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getHomeOwnerPhone() {
        return homeOwnerPhone;
    }

    /**
     * Sets the value of the homeOwnerPhone property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHomeOwnerPhone(String value) {
        this.homeOwnerPhone = value;
    }

    /**
     * Gets the value of the exactAddress property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getExactAddress() {
        return exactAddress;
    }

    /**
     * Sets the value of the exactAddress property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setExactAddress(String value) {
        this.exactAddress = value;
    }

    /**
     * Gets the value of the cadastralNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCadastralNumber() {
        return cadastralNumber;
    }

    /**
     * Sets the value of the cadastralNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCadastralNumber(String value) {
        this.cadastralNumber = value;
    }

}
