//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 03:03:52 PM MSK 
//


package com.baltinfo.radius.feed.cian.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FlatNumber" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="SectionNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FlatType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "flatNumber",
        "sectionNumber",
        "flatType"
})
public class Flat {

    @XmlElement(name = "FlatNumber")
    protected BigInteger flatNumber;
    @XmlElement(name = "SectionNumber")
    protected String sectionNumber;
    @XmlElement(name = "FlatType")
    protected String flatType;

    /**
     * Gets the value of the flatNumber property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getFlatNumber() {
        return flatNumber;
    }

    /**
     * Sets the value of the flatNumber property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setFlatNumber(BigInteger value) {
        this.flatNumber = value;
    }

    /**
     * Gets the value of the sectionNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSectionNumber() {
        return sectionNumber;
    }

    /**
     * Sets the value of the sectionNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSectionNumber(String value) {
        this.sectionNumber = value;
    }

    /**
     * Gets the value of the flatType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFlatType() {
        return flatType;
    }

    /**
     * Sets the value of the flatType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFlatType(String value) {
        this.flatType = value;
    }

}
