//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 03:03:52 PM MSK 
//


package com.baltinfo.radius.feed.cian.model;

import com.baltinfo.radius.feed.utils.DoubleExponentAdapter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Auction" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Bet" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ExternalId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Coordinates" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Lat" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *                   &lt;element name="Lng" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CadastralNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Phones">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PhoneSchema" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Highway" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="Distance" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Undergrounds" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="UndergroundInfoSchema" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                             &lt;element name="Time" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                             &lt;element name="TransportType" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="transport"/>
 *                                   &lt;enumeration value="walk"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TotalArea" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="MinArea" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="FloorNumber" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="ConditionType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="cosmeticRepairsRequired"/>
 *               &lt;enumeration value="finishing"/>
 *               &lt;enumeration value="majorRepairsRequired"/>
 *               &lt;enumeration value="office"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="JKSchema" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="House" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Flat" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="FlatNumber" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                                       &lt;element name="SectionNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="FlatType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SubAgent" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="AvatarUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="IsOccupied" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Layout" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="cabinet"/>
 *               &lt;enumeration value="mixed"/>
 *               &lt;enumeration value="openSpace"/>
 *               &lt;enumeration value="corridorplan"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FurniturePresence" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="no"/>
 *               &lt;enumeration value="yes"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LayoutPhoto" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FullUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="IsDefault" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Photos" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PhotoSchema" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="FullUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="IsDefault" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AvailableFrom" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IsLegalAddressProvided" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="WaterPipesCount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="TaxNumber" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="IsInHiddenBase" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="BusinessShoppingCenter" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Videos" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="VideoSchema" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Building">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="FloorsCount" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="BuildYear" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="MaterialType" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="block"/>
 *                         &lt;enumeration value="boards"/>
 *                         &lt;enumeration value="brick"/>
 *                         &lt;enumeration value="monolith"/>
 *                         &lt;enumeration value="monolithBrick"/>
 *                         &lt;enumeration value="old"/>
 *                         &lt;enumeration value="panel"/>
 *                         &lt;enumeration value="stalin"/>
 *                         &lt;enumeration value="wood"/>
 *                         &lt;enumeration value="wireframe"/>
 *                         &lt;enumeration value="aerocreteBlock"/>
 *                         &lt;enumeration value="gasSilicateBlock"/>
 *                         &lt;enumeration value="foamConcreteBlock"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="TotalArea" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="HeatingType" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="autonomous"/>
 *                         &lt;enumeration value="central"/>
 *                         &lt;enumeration value="no"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CeilingHeight" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *                   &lt;element name="Parking" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Type" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="ground"/>
 *                                   &lt;enumeration value="multilevel"/>
 *                                   &lt;enumeration value="roof"/>
 *                                   &lt;enumeration value="underground"/>
 *                                   &lt;enumeration value="open"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="PlacesCount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                             &lt;element name="PriceMonthly" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *                             &lt;element name="Currency" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="eur"/>
 *                                   &lt;enumeration value="rur"/>
 *                                   &lt;enumeration value="usd"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="IsFree" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Type" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="administrativeBuilding"/>
 *                         &lt;enumeration value="businessCenter"/>
 *                         &lt;enumeration value="businessCenter2"/>
 *                         &lt;enumeration value="businessPark"/>
 *                         &lt;enumeration value="businessQuarter"/>
 *                         &lt;enumeration value="free"/>
 *                         &lt;enumeration value="industrialComplex"/>
 *                         &lt;enumeration value="industrialPark"/>
 *                         &lt;enumeration value="industrialSite"/>
 *                         &lt;enumeration value="industrialWarehouseComplex"/>
 *                         &lt;enumeration value="logisticsCenter"/>
 *                         &lt;enumeration value="logisticsComplex"/>
 *                         &lt;enumeration value="mansion"/>
 *                         &lt;enumeration value="manufactureBuilding"/>
 *                         &lt;enumeration value="manufacturingFacility"/>
 *                         &lt;enumeration value="modular"/>
 *                         &lt;enumeration value="multifunctionalComplex"/>
 *                         &lt;enumeration value="officeAndHotelComplex"/>
 *                         &lt;enumeration value="officeAndResidentialComplex"/>
 *                         &lt;enumeration value="officeAndWarehouse"/>
 *                         &lt;enumeration value="officeAndWarehouseComplex"/>
 *                         &lt;enumeration value="officeBuilding"/>
 *                         &lt;enumeration value="officeIndustrialComplex"/>
 *                         &lt;enumeration value="old"/>
 *                         &lt;enumeration value="other"/>
 *                         &lt;enumeration value="outlet"/>
 *                         &lt;enumeration value="propertyComplex"/>
 *                         &lt;enumeration value="residentialComplex"/>
 *                         &lt;enumeration value="residentialHouse"/>
 *                         &lt;enumeration value="shoppingAndBusinessComplex"/>
 *                         &lt;enumeration value="shoppingAndCommunityCenter"/>
 *                         &lt;enumeration value="shoppingAndEntertainmentCenter"/>
 *                         &lt;enumeration value="shoppingCenter"/>
 *                         &lt;enumeration value="specializedShoppingCenter"/>
 *                         &lt;enumeration value="standaloneBuilding"/>
 *                         &lt;enumeration value="technopark"/>
 *                         &lt;enumeration value="tradingOfficeComplex"/>
 *                         &lt;enumeration value="warehouse"/>
 *                         &lt;enumeration value="warehouseComplex"/>
 *                         &lt;enumeration value="officeQuarter"/>
 *                         &lt;enumeration value="officeCenter"/>
 *                         &lt;enumeration value="businessQuarter2"/>
 *                         &lt;enumeration value="businessHouse"/>
 *                         &lt;enumeration value="tradingHouse"/>
 *                         &lt;enumeration value="officeComplex"/>
 *                         &lt;enumeration value="tradeAndExhibitionComplex"/>
 *                         &lt;enumeration value="shoppingComplex"/>
 *                         &lt;enumeration value="shoppingAndWarehouseComplex"/>
 *                         &lt;enumeration value="logisticsPark"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ClassType" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="a"/>
 *                         &lt;enumeration value="aPlus"/>
 *                         &lt;enumeration value="b"/>
 *                         &lt;enumeration value="bMinus"/>
 *                         &lt;enumeration value="bPlus"/>
 *                         &lt;enumeration value="c"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Developer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ManagementCompany" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="VentilationType" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="forced"/>
 *                         &lt;enumeration value="natural"/>
 *                         &lt;enumeration value="no"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ConditioningType" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="central"/>
 *                         &lt;enumeration value="local"/>
 *                         &lt;enumeration value="no"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ExtinguishingSystemType" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="alarm"/>
 *                         &lt;enumeration value="gas"/>
 *                         &lt;enumeration value="hydrant"/>
 *                         &lt;enumeration value="no"/>
 *                         &lt;enumeration value="powder"/>
 *                         &lt;enumeration value="sprinkler"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ExtinguishingSystemTypes" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ExtinguishingSystemTypeEnum" maxOccurs="unbounded">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="alarm"/>
 *                                   &lt;enumeration value="gas"/>
 *                                   &lt;enumeration value="hydrant"/>
 *                                   &lt;enumeration value="no"/>
 *                                   &lt;enumeration value="powder"/>
 *                                   &lt;enumeration value="sprinkler"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="StatusType" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="operational"/>
 *                         &lt;enumeration value="project"/>
 *                         &lt;enumeration value="underConstruction"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="AccessType" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="free"/>
 *                         &lt;enumeration value="passSystem"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Infrastructure" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="HasCarWash" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="HasBuffet" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="HasCarService" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="HasCanteen" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="HasCentralReception" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="HasHotel" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="HasAtm" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="HasExhibitionAndWarehouseComplex" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="HasPharmacy" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="HasBankDepartment" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="HasCinema" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="HasCafe" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="HasMedicalCenter" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="HasBeautyShop" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="HasStudio" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="HasNotaryOffice" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="HasPool" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="HasClothesStudio" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="HasWarehouse" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="HasPark" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="HasRestaurant" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="HasFitnessCentre" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="HasSupermarket" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="HasMinimarket" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="HasShoppingArea" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="HasConferenceRoom" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Land">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Area" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="AreaUnitType">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="hectare"/>
 *                         &lt;enumeration value="sotka"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Type" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="owned"/>
 *                         &lt;enumeration value="rent"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RentByPartsDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PublishTerms" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Terms" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="PublishTermSchema" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Services" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="ServicesEnum" maxOccurs="unbounded">
 *                                                   &lt;simpleType>
 *                                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                       &lt;enumeration value="free"/>
 *                                                       &lt;enumeration value="highlight"/>
 *                                                       &lt;enumeration value="paid"/>
 *                                                       &lt;enumeration value="premium"/>
 *                                                       &lt;enumeration value="top3"/>
 *                                                     &lt;/restriction>
 *                                                   &lt;/simpleType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="ExcludedServices" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="ExcludedServicesEnum" maxOccurs="unbounded">
 *                                                   &lt;simpleType>
 *                                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                       &lt;enumeration value="highlight"/>
 *                                                       &lt;enumeration value="premium"/>
 *                                                       &lt;enumeration value="top3"/>
 *                                                     &lt;/restriction>
 *                                                   &lt;/simpleType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="IgnoreServicePackages" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ExtraData" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="HomeOwnerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="HomeOwnerPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ExactAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="CadastralNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BargainTerms">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Price" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="Currency" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="eur"/>
 *                         &lt;enumeration value="rur"/>
 *                         &lt;enumeration value="usd"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="VatType" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="included"/>
 *                         &lt;enumeration value="notIncluded"/>
 *                         &lt;enumeration value="vatIncluded"/>
 *                         &lt;enumeration value="vatNotIncluded"/>
 *                         &lt;enumeration value="usn"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="VatPrice" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *                   &lt;element name="ContractType" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="leaseAssignment"/>
 *                         &lt;enumeration value="sale"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="AgentBonus" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *                             &lt;element name="PaymentType" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="percent"/>
 *                                   &lt;enumeration value="fixed"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Currency" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="eur"/>
 *                                   &lt;enumeration value="rur"/>
 *                                   &lt;enumeration value="usd"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "category",
        "auction",
        "externalId",
        "description",
        "address",
        "coordinates",
        "cadastralNumber",
        "phones",
        "highway",
        "undergrounds",
        "totalArea",
        "minArea",
        "floorNumber",
        "flatRoomsCount",
        "conditionType",
        "jkSchema",
        "subAgent",
        "isOccupied",
        "layout",
        "furniturePresence",
        "layoutPhoto",
        "photos",
        "availableFrom",
        "isLegalAddressProvided",
        "waterPipesCount",
        "taxNumber",
        "isInHiddenBase",
        "businessShoppingCenter",
        "videos",
        "title",
        "building",
        "land",
        "rentByPartsDescription",
        "publishTerms",
        "extraData",
        "bargainTerms",
        "garage",
        "shareAmount",
        "roomArea"
})
public class Object {

    @XmlElement(name = "Category", required = true)
    protected String category;
    @XmlElement(name = "Auction")
    protected Auction auction;
    @XmlElement(name = "ExternalId", required = true)
    protected String externalId;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "Address", required = true)
    protected String address;
    @XmlElement(name = "Coordinates")
    protected Coordinates coordinates;
    @XmlElement(name = "CadastralNumber")
    protected String cadastralNumber;
    @XmlElement(name = "Phones", required = true)
    protected Phones phones;
    @XmlElement(name = "Highway")
    protected Highway highway;
    @XmlElement(name = "Undergrounds")
    protected Undergrounds undergrounds;
    @XmlElement(name = "TotalArea")
    @XmlJavaTypeAdapter(type = Double.class, value = DoubleExponentAdapter.class)
    protected Double totalArea;
    @XmlElement(name = "MinArea")
    @XmlJavaTypeAdapter(type = Double.class, value = DoubleExponentAdapter.class)
    protected Double minArea;
    @XmlElement(name = "FloorNumber")
    protected BigInteger floorNumber;
    @XmlElement(name = "FlatRoomsCount")
    protected Integer flatRoomsCount;
    @XmlElement(name = "ConditionType")
    protected String conditionType;
    @XmlElement(name = "JKSchema")
    protected JKSchema jkSchema;
    @XmlElement(name = "SubAgent")
    protected SubAgent subAgent;
    @XmlElement(name = "IsOccupied")
    protected Boolean isOccupied;
    @XmlElement(name = "Layout")
    protected String layout;
    @XmlElement(name = "FurniturePresence")
    protected String furniturePresence;
    @XmlElement(name = "LayoutPhoto")
    protected LayoutPhoto layoutPhoto;
    @XmlElement(name = "Photos")
    protected Photos photos;
    @XmlElement(name = "AvailableFrom")
    protected String availableFrom;
    @XmlElement(name = "IsLegalAddressProvided")
    protected Boolean isLegalAddressProvided;
    @XmlElement(name = "WaterPipesCount")
    protected BigInteger waterPipesCount;
    @XmlElement(name = "TaxNumber")
    protected BigInteger taxNumber;
    @XmlElement(name = "IsInHiddenBase")
    protected Boolean isInHiddenBase;
    @XmlElement(name = "BusinessShoppingCenter")
    protected BusinessShoppingCenter businessShoppingCenter;
    @XmlElement(name = "Videos")
    protected Videos videos;
    @XmlElement(name = "Title")
    protected String title;
    @XmlElement(name = "Building")
    protected Building building;
    @XmlElement(name = "Land")
    protected Land land;
    @XmlElement(name = "RentByPartsDescription")
    protected String rentByPartsDescription;
    @XmlElement(name = "PublishTerms")
    protected PublishTerms publishTerms;
    @XmlElement(name = "ExtraData")
    protected ExtraData extraData;
    @XmlElement(name = "BargainTerms")
    protected BargainTerms bargainTerms;
    @XmlElement(name = "Garage")
    protected Garage garage;
    @XmlElement(name = "ShareAmount")
    protected String shareAmount;
    @XmlElement(name = "RoomArea")
    @XmlJavaTypeAdapter(type = Double.class, value = DoubleExponentAdapter.class)
    protected Double roomArea;

    /**
     * Gets the value of the category property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the auction property.
     *
     * @return possible object is
     * {@link Auction }
     */
    public Auction getAuction() {
        return auction;
    }

    /**
     * Sets the value of the auction property.
     *
     * @param value allowed object is
     *              {@link Auction }
     */
    public void setAuction(Auction value) {
        this.auction = value;
    }

    /**
     * Gets the value of the externalId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getExternalId() {
        return externalId;
    }

    /**
     * Sets the value of the externalId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setExternalId(String value) {
        this.externalId = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the address property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the coordinates property.
     *
     * @return possible object is
     * {@link Coordinates }
     */
    public Coordinates getCoordinates() {
        return coordinates;
    }

    /**
     * Sets the value of the coordinates property.
     *
     * @param value allowed object is
     *              {@link Coordinates }
     */
    public void setCoordinates(Coordinates value) {
        this.coordinates = value;
    }

    /**
     * Gets the value of the cadastralNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCadastralNumber() {
        return cadastralNumber;
    }

    /**
     * Sets the value of the cadastralNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCadastralNumber(String value) {
        this.cadastralNumber = value;
    }

    /**
     * Gets the value of the phones property.
     *
     * @return possible object is
     * {@link Phones }
     */
    public Phones getPhones() {
        return phones;
    }

    /**
     * Sets the value of the phones property.
     *
     * @param value allowed object is
     *              {@link Phones }
     */
    public void setPhones(Phones value) {
        this.phones = value;
    }

    /**
     * Gets the value of the highway property.
     *
     * @return possible object is
     * {@link Highway }
     */
    public Highway getHighway() {
        return highway;
    }

    /**
     * Sets the value of the highway property.
     *
     * @param value allowed object is
     *              {@link Highway }
     */
    public void setHighway(Highway value) {
        this.highway = value;
    }

    /**
     * Gets the value of the undergrounds property.
     *
     * @return possible object is
     * {@link Undergrounds }
     */
    public Undergrounds getUndergrounds() {
        return undergrounds;
    }

    /**
     * Sets the value of the undergrounds property.
     *
     * @param value allowed object is
     *              {@link Undergrounds }
     */
    public void setUndergrounds(Undergrounds value) {
        this.undergrounds = value;
    }

    /**
     * Gets the value of the totalArea property.
     */
    public Double getTotalArea() {
        return totalArea;
    }

    /**
     * Sets the value of the totalArea property.
     */
    public void setTotalArea(Double value) {
        this.totalArea = value;
    }

    /**
     * Gets the value of the minArea property.
     *
     * @return possible object is
     * {@link Double }
     */
    public Double getMinArea() {
        return minArea;
    }

    /**
     * Sets the value of the minArea property.
     *
     * @param value allowed object is
     *              {@link Double }
     */
    public void setMinArea(Double value) {
        this.minArea = value;
    }

    /**
     * Gets the value of the floorNumber property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getFloorNumber() {
        return floorNumber;
    }

    /**
     * Sets the value of the floorNumber property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setFloorNumber(BigInteger value) {
        this.floorNumber = value;
    }

    /**
     * Gets the value of the flatRoomsCount property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getFlatRoomsCount() {
        return flatRoomsCount;
    }

    /**
     * Sets the value of the floorNumber property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setFlatRoomsCount(Integer value) {
        this.flatRoomsCount = value;
    }

    /**
     * Gets the value of the conditionType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getConditionType() {
        return conditionType;
    }

    /**
     * Sets the value of the conditionType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setConditionType(String value) {
        this.conditionType = value;
    }

    /**
     * Gets the value of the jkSchema property.
     *
     * @return possible object is
     * {@link JKSchema }
     */
    public JKSchema getJKSchema() {
        return jkSchema;
    }

    /**
     * Sets the value of the jkSchema property.
     *
     * @param value allowed object is
     *              {@link JKSchema }
     */
    public void setJKSchema(JKSchema value) {
        this.jkSchema = value;
    }

    /**
     * Gets the value of the subAgent property.
     *
     * @return possible object is
     * {@link SubAgent }
     */
    public SubAgent getSubAgent() {
        return subAgent;
    }

    /**
     * Sets the value of the subAgent property.
     *
     * @param value allowed object is
     *              {@link SubAgent }
     */
    public void setSubAgent(SubAgent value) {
        this.subAgent = value;
    }

    /**
     * Gets the value of the isOccupied property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isIsOccupied() {
        return isOccupied;
    }

    /**
     * Sets the value of the isOccupied property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setIsOccupied(Boolean value) {
        this.isOccupied = value;
    }

    /**
     * Gets the value of the layout property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLayout() {
        return layout;
    }

    /**
     * Sets the value of the layout property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLayout(String value) {
        this.layout = value;
    }

    /**
     * Gets the value of the furniturePresence property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFurniturePresence() {
        return furniturePresence;
    }

    /**
     * Sets the value of the furniturePresence property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFurniturePresence(String value) {
        this.furniturePresence = value;
    }

    /**
     * Gets the value of the layoutPhoto property.
     *
     * @return possible object is
     * {@link LayoutPhoto }
     */
    public LayoutPhoto getLayoutPhoto() {
        return layoutPhoto;
    }

    /**
     * Sets the value of the layoutPhoto property.
     *
     * @param value allowed object is
     *              {@link LayoutPhoto }
     */
    public void setLayoutPhoto(LayoutPhoto value) {
        this.layoutPhoto = value;
    }

    /**
     * Gets the value of the photos property.
     *
     * @return possible object is
     * {@link Photos }
     */
    public Photos getPhotos() {
        return photos;
    }

    /**
     * Sets the value of the photos property.
     *
     * @param value allowed object is
     *              {@link Photos }
     */
    public void setPhotos(Photos value) {
        this.photos = value;
    }

    /**
     * Gets the value of the availableFrom property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAvailableFrom() {
        return availableFrom;
    }

    /**
     * Sets the value of the availableFrom property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAvailableFrom(String value) {
        this.availableFrom = value;
    }

    /**
     * Gets the value of the isLegalAddressProvided property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isIsLegalAddressProvided() {
        return isLegalAddressProvided;
    }

    /**
     * Sets the value of the isLegalAddressProvided property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setIsLegalAddressProvided(Boolean value) {
        this.isLegalAddressProvided = value;
    }

    /**
     * Gets the value of the waterPipesCount property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getWaterPipesCount() {
        return waterPipesCount;
    }

    /**
     * Sets the value of the waterPipesCount property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setWaterPipesCount(BigInteger value) {
        this.waterPipesCount = value;
    }

    /**
     * Gets the value of the taxNumber property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getTaxNumber() {
        return taxNumber;
    }

    /**
     * Sets the value of the taxNumber property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setTaxNumber(BigInteger value) {
        this.taxNumber = value;
    }

    /**
     * Gets the value of the isInHiddenBase property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isIsInHiddenBase() {
        return isInHiddenBase;
    }

    /**
     * Sets the value of the isInHiddenBase property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setIsInHiddenBase(Boolean value) {
        this.isInHiddenBase = value;
    }

    /**
     * Gets the value of the businessShoppingCenter property.
     *
     * @return possible object is
     * {@link BusinessShoppingCenter }
     */
    public BusinessShoppingCenter getBusinessShoppingCenter() {
        return businessShoppingCenter;
    }

    /**
     * Sets the value of the businessShoppingCenter property.
     *
     * @param value allowed object is
     *              {@link BusinessShoppingCenter }
     */
    public void setBusinessShoppingCenter(BusinessShoppingCenter value) {
        this.businessShoppingCenter = value;
    }

    /**
     * Gets the value of the videos property.
     *
     * @return possible object is
     * {@link Videos }
     */
    public Videos getVideos() {
        return videos;
    }

    /**
     * Sets the value of the videos property.
     *
     * @param value allowed object is
     *              {@link Videos }
     */
    public void setVideos(Videos value) {
        this.videos = value;
    }

    /**
     * Gets the value of the title property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the building property.
     *
     * @return possible object is
     * {@link Building }
     */
    public Building getBuilding() {
        return building;
    }

    /**
     * Sets the value of the building property.
     *
     * @param value allowed object is
     *              {@link Building }
     */
    public void setBuilding(Building value) {
        this.building = value;
    }

    /**
     * Gets the value of the land property.
     *
     * @return possible object is
     * {@link Land }
     */
    public Land getLand() {
        return land;
    }

    /**
     * Sets the value of the land property.
     *
     * @param value allowed object is
     *              {@link Land }
     */
    public void setLand(Land value) {
        this.land = value;
    }

    /**
     * Gets the value of the rentByPartsDescription property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRentByPartsDescription() {
        return rentByPartsDescription;
    }

    /**
     * Sets the value of the rentByPartsDescription property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRentByPartsDescription(String value) {
        this.rentByPartsDescription = value;
    }

    /**
     * Gets the value of the publishTerms property.
     *
     * @return possible object is
     * {@link PublishTerms }
     */
    public PublishTerms getPublishTerms() {
        return publishTerms;
    }

    /**
     * Sets the value of the publishTerms property.
     *
     * @param value allowed object is
     *              {@link PublishTerms }
     */
    public void setPublishTerms(PublishTerms value) {
        this.publishTerms = value;
    }

    /**
     * Gets the value of the extraData property.
     *
     * @return possible object is
     * {@link ExtraData }
     */
    public ExtraData getExtraData() {
        return extraData;
    }

    /**
     * Sets the value of the extraData property.
     *
     * @param value allowed object is
     *              {@link ExtraData }
     */
    public void setExtraData(ExtraData value) {
        this.extraData = value;
    }

    /**
     * Gets the value of the bargainTerms property.
     *
     * @return possible object is
     * {@link BargainTerms }
     */
    public BargainTerms getBargainTerms() {
        return bargainTerms;
    }

    /**
     * Sets the value of the bargainTerms property.
     *
     * @param value allowed object is
     *              {@link BargainTerms }
     */
    public void setBargainTerms(BargainTerms value) {
        this.bargainTerms = value;
    }

    public Garage getGarage() {
        return garage;
    }

    public void setGarage(Garage garage) {
        this.garage = garage;
    }

    public String getShareAmount() {
        return shareAmount;
    }

    public void setShareAmount(String shareAmount) {
        this.shareAmount = shareAmount;
    }

    public Double getRoomArea() {
        return roomArea;
    }

    public void setRoomArea(Double roomArea) {
        this.roomArea = roomArea;
    }
}
