//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 03:03:52 PM MSK 
//


package com.baltinfo.radius.feed.cian.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Type" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="ground"/>
 *               &lt;enumeration value="multilevel"/>
 *               &lt;enumeration value="roof"/>
 *               &lt;enumeration value="underground"/>
 *               &lt;enumeration value="open"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PlacesCount" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="PriceMonthly" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="Currency" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="eur"/>
 *               &lt;enumeration value="rur"/>
 *               &lt;enumeration value="usd"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IsFree" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "type",
        "placesCount",
        "priceMonthly",
        "currency",
        "isFree"
})
public class Parking {

    @XmlElement(name = "Type")
    protected String type;
    @XmlElement(name = "PlacesCount")
    protected BigInteger placesCount;
    @XmlElement(name = "PriceMonthly")
    protected Double priceMonthly;
    @XmlElement(name = "Currency")
    protected String currency;
    @XmlElement(name = "IsFree")
    protected Boolean isFree;

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the placesCount property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getPlacesCount() {
        return placesCount;
    }

    /**
     * Sets the value of the placesCount property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setPlacesCount(BigInteger value) {
        this.placesCount = value;
    }

    /**
     * Gets the value of the priceMonthly property.
     *
     * @return possible object is
     * {@link Double }
     */
    public Double getPriceMonthly() {
        return priceMonthly;
    }

    /**
     * Sets the value of the priceMonthly property.
     *
     * @param value allowed object is
     *              {@link Double }
     */
    public void setPriceMonthly(Double value) {
        this.priceMonthly = value;
    }

    /**
     * Gets the value of the currency property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the isFree property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isIsFree() {
        return isFree;
    }

    /**
     * Sets the value of the isFree property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setIsFree(Boolean value) {
        this.isFree = value;
    }

}
