//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.24 at 03:03:52 PM MSK 
//


package com.baltinfo.radius.feed.cian.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Services" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ServicesEnum" maxOccurs="unbounded">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="free"/>
 *                         &lt;enumeration value="highlight"/>
 *                         &lt;enumeration value="paid"/>
 *                         &lt;enumeration value="premium"/>
 *                         &lt;enumeration value="top3"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ExcludedServices" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ExcludedServicesEnum" maxOccurs="unbounded">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="highlight"/>
 *                         &lt;enumeration value="premium"/>
 *                         &lt;enumeration value="top3"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="IgnoreServicePackages" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "services",
        "excludedServices",
        "ignoreServicePackages"
})
public class PublishTermSchema {

    @XmlElement(name = "Services")
    protected Services services;
    @XmlElement(name = "ExcludedServices")
    protected ExcludedServices excludedServices;
    @XmlElement(name = "IgnoreServicePackages")
    protected Boolean ignoreServicePackages;

    /**
     * Gets the value of the services property.
     *
     * @return possible object is
     * {@link Services }
     */
    public Services getServices() {
        return services;
    }

    /**
     * Sets the value of the services property.
     *
     * @param value allowed object is
     *              {@link Services }
     */
    public void setServices(Services value) {
        this.services = value;
    }

    /**
     * Gets the value of the excludedServices property.
     *
     * @return possible object is
     * {@link ExcludedServices }
     */
    public ExcludedServices getExcludedServices() {
        return excludedServices;
    }

    /**
     * Sets the value of the excludedServices property.
     *
     * @param value allowed object is
     *              {@link ExcludedServices }
     */
    public void setExcludedServices(ExcludedServices value) {
        this.excludedServices = value;
    }

    /**
     * Gets the value of the ignoreServicePackages property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isIgnoreServicePackages() {
        return ignoreServicePackages;
    }

    /**
     * Sets the value of the ignoreServicePackages property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setIgnoreServicePackages(Boolean value) {
        this.ignoreServicePackages = value;
    }

}
