//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.10 at 04:51:35 PM MSK 
//


package com.baltinfo.radius.avito.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ModificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Make" type="{}MakeType" minOccurs="0"/>
 *         &lt;element name="Model" type="{}ModelType" minOccurs="0"/>
 *         &lt;element name="YearFrom" type="{}YearFromType" minOccurs="0"/>
 *         &lt;element name="YearTo" type="{}YearToType" minOccurs="0"/>
 *         &lt;element name="BodyType" type="{}BodyTypeType" minOccurs="0"/>
 *         &lt;element name="Doors" type="{}DoorsType" minOccurs="0"/>
 *         &lt;element name="Generation" type="{}GenerationType" minOccurs="0"/>
 *         &lt;element name="FuelType" type="{}FuelTypeType" minOccurs="0"/>
 *         &lt;element name="DriveType" type="{}DriveTypeType" minOccurs="0"/>
 *         &lt;element name="Transmission" type="{}TransmissionType" minOccurs="0"/>
 *         &lt;element name="Modification" type="{}ModificationType" minOccurs="0"/>
 *         &lt;element name="Power" type="{}PowerType" minOccurs="0"/>
 *         &lt;element name="EngineSize" type="{}EngineSizeType" minOccurs="0"/>
 *         &lt;element name="Complectations" type="{}ComplectationsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModificationType", propOrder = {
    "content"
})
public class ModificationType {

    @XmlElementRefs({
        @XmlElementRef(name = "YearTo", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Power", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Transmission", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "YearFrom", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Modification", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Complectations", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Doors", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "DriveType", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Generation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Make", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "EngineSize", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Model", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BodyType", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "FuelType", type = JAXBElement.class, required = false)
    })
    @XmlMixed
    protected List<Serializable> content;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link YearToType }{@code >}
     * {@link JAXBElement }{@code <}{@link PowerType }{@code >}
     * {@link String }
     * {@link JAXBElement }{@code <}{@link TransmissionType }{@code >}
     * {@link JAXBElement }{@code <}{@link YearFromType }{@code >}
     * {@link JAXBElement }{@code <}{@link ModificationType }{@code >}
     * {@link JAXBElement }{@code <}{@link ComplectationsType }{@code >}
     * {@link JAXBElement }{@code <}{@link DoorsType }{@code >}
     * {@link JAXBElement }{@code <}{@link DriveTypeType }{@code >}
     * {@link JAXBElement }{@code <}{@link GenerationType }{@code >}
     * {@link JAXBElement }{@code <}{@link MakeType }{@code >}
     * {@link JAXBElement }{@code <}{@link EngineSizeType }{@code >}
     * {@link JAXBElement }{@code <}{@link ModelType }{@code >}
     * {@link JAXBElement }{@code <}{@link BodyTypeType }{@code >}
     * {@link JAXBElement }{@code <}{@link FuelTypeType }{@code >}
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
