package com.baltinfo.radius.loadauction.constants;

/**
 * @author Kulikov Semyon
 * @since 02.03.2020
 */

public enum LabelsConformity {
    TYPE_ASSET("Классификатор"),
    ID_SYA("ID-СУА"),
    NAME_ASSET("Наименование"),
    LOCATION_ASSET("Субъект Федерации"),
    NAME_FO_ASSET("Наименование ФО"),
    ABOUT_ASSET("Описание"),
    ABOUT("Описание залога"),
    DEPOSITS("Является залогом"),
    OTHER("Прочее"),
    RESTRICTIONS_ASSET("Ограничения и обременения"),
    DOCUMENTS_ASSET(""),
    IMAGES_ASSET(""),
    TYPE_OF_OBJECT("Тип"),
    SQUARE("Площадь"),
    ADDRESS("Адрес"),
    CADASTRAL_NUMBER("Кадастровый номер"),
    YEAR_BUILT("Год постройки"),
    NUMBER_OF_ROOMS("Кол-во комнат"),
    FLOOR_NUMBER("Номер этажа"),
    FLOORS("Этажность"),
    CEILING_HEIGHT("Высота потолков"),
    LIVING_SPACE("Жилая площадь"),
    KITCHEN_AREA("Площадь кухни"),
    ELEVATOR("Наличие лифта"),
    HOUSE_TYPE("Тип дома"),
    BALCONY("Лоджия/балкон"),
    VIEW_FROM_THE_WINDOW("Вид из окна"),
    COMMUNICATIONS("Коммуникации и их характеристики"),
    ASSESSMENT_VALUE("Оценочная стоимость"),
    ASSESSMENT_DATE("Дата оценки"),
    TYPE_OF_ASSET("Тип"),
    NAME_PRODUCT("Наименование"),
    AUTHOR("Автор"),
    DATE("Дата создания"),
    SIZE("Размер"),
    MATERIAL("Материал"),
    EXPERTISE_INFORMATION("Информация об экспертизе"),
    VIEW("Вид"),
    PROMISER("Векселедатель"),
    PROMISER_INN("ИНН векселедателя"),
    INTEREST_RATE("Процентная ставка"),
    BILL_AMOUNT("Вексельная сумма"),
    CURRENCY("Валюта"),
    DATE_OF_PREPARATION("Дата составления"),
    PLACE_OF_COMPILATION("Место составления"),
    OBLIGATED_PERSON_NAME("Наименование обязательного лица"),
    AVALIST("Авалист"),
    PAYMENT_TERM("Срок платежа"),
    PLACE_OF_PAYMENT("Место платежа"),
    PROMISER_LOCATION("Местонахождение векселедателя"),
    STORAGE("Место хранения"),
    PROMISER_BANKROT("Банкротство векселедателя"),
    URL("Ссылки"),
    TYPE_BOND("Вид"),
    ISSUER_NAME("Наименование эмитента"),
    ISSUER_INN("ИНН эмитента"),
    AMOUNT("Количество"),
    COUPON_RATE("Ставка купонного дохода"),
    PAYMENT_FREQUENCY("Периодичность выплаты"),
    MATURITY_DATE("Дата погашения"),
    REGISTRATION_NUMBER("Регистрационный номер"),
    ISIN("ISIN"),
    NOMINAL_COST("Номинальная стоимость"),
    ISSUER_LOCATION("Местонахождение эмитента"),
    DEFAULT("Дефолт"),
    BANKRUPYCY_OF_THE_ISSUER("Банкротство эмитента"),
    CREDIT_TYPE("Тип кредита"),
    AVERAGE_INTEREST_RATE("Процентная ставка"),
    AVERAGE_REPAYMENT_DATE("Дата погашения"),
    DEBT_REPAYMENT_METHOD("Способ погашения задолженности"),
    AVAILABILITY("Наличие обеспечения"),
    DESCRIPTION_PLEDGES("Описание залогов"),
    KD("№ КД (судебного решения)"),
    NAME_CB("Наименование ценной  бумаги"),
    BALANCE_DATE("Дата баланса"),
    DATE_KD("Дата заключения договора"),
    AMOUNT_OF_BALANCE("Размер задолженности на текущую дату"),
    DOCUMENT_STORAGE("Место хранения документов"),
    OVERDUE("Кол-во дней просроченного платежа"),
    TRIAL("Наличие судебных разбирательств"),
    END_DATE("Дата последнего погашения"),
    MARK("Марка"),
    MODEL("Модель"),
    COLOR("Цвет"),
    YEAR_OF_ISSUE("Год выпуска"),
    MILEAGE("Пробег"),
    ENGINE_CAPACITY("Объем двигателя"),
    CAR_BODY("Тип кузова"),
    STEERING_WHEEL("Тип руля"),
    TRANSMISSION("Коробка передач"),
    ENGINE_POWER("Мощность двигателя"),
    ENGINE_TYPE("Тип двигателя"),
    TYPE_OF_DRIVE("Тип привода"),
    VIN("VIN-код"),
    NAME("Наименование"),
    COUNTRY("Страна"),
    SERIES("Серия"),
    METAL("Металл"),
    SAMPLE("Проба"),
    WEIGHT("Масса"),
    CATEGOR("Категория"),
    READINESS("Готовность"),
    GARAGE_TYPE("Тип гаража"),
    TYPE_OF_PARKING("Тип машиноместа"),
    PRESENCE_OF_SECURITY("Наличие охраны"),
    TOTAL_WEIGHT("Вес"),
    NAME_STONE("Камень"),
    NUMBER_OF_FLOORS("Этажность"),
    MORE_ABOUT_NUMBER_OF_FLOORS("Подробнее об этажности"),
    WALL_MATERIAL("Материал стен"),
    ROOFING_MATERIAL("Материал кровли"),
    TRANSPORT_ACCESSIBILITY("Транспортная доступность"),
    FOUNDATION("Фундамент"),
    NAME_RIGHTHOLDER("Наименование правообладателя"),
    NUMBER_OF_SVIDET("Номер свидетельства"),
    FUND_NAME("Наименование фонда"),
    FUND_CATEGORY("Категория фонда"),
    FUND_TYPE("Тип фонда"),
    TERM_TlabelT_MANAGEMENT("Срок доверительного управления"),
    NUMBER_OF_SHARES("Кол-во паев"),
    NUMBER_OF_SHARES_PERCENT("Кол-во паев, % от общего кол-ва"),
    STORAGE_OF_SHARES("Место хранения паев"),
    MANAGEMENT_COMPANY_NAME("Наименование управляющей компании"),
    INTERVALS("Интервалы"),
    MAIN_ASSETS_OF_THE_FUND("Основное имущество, составляющее фонд"),
    LAND_CATEGORY("Категория земель"),
    PERMITTED_USE("Разрешенное использование"),
    DISTANCE_TO_THE_REGIONAL_CENTER("Расстояние до областного центра"),
    BORROWER_NAME("Наименование заемщика"),
    BORROWER_INN("ИНН заемщика"),
    ISU_NAME("Наименование ИСУ"),
    MANAGEMENT_COMPANY("Управляющая компания"),
    AMOUNT_PERCENT("% от общего кол-ва"),
    MORTGAGE_COVERAGE("Основное имущество, составляющее ипотечное покрытие"),
    TYPE_CB("Вид"),
    ISSUER("Эмитент"),
    NUMBER("Номер"),
    TERM("Срок"),
    SUPPORTING_DOCUMENTS("Подтверждающие документы"),
    COUNTERPARTY("Контрагент"),
    ASSOCIATION_NAME("Наименование общества"),
    ASSOCIATION_INN("ИНН общества"),
    SHARE("Доля"),
    SHARE_FO("Доля ФО"),
    REAL_ACTIVITY("Реальный вид деятельности"),
    ASSOCIATION_LOCATION("Местонахождение общества"),
    TURNOVER_LIMIT("Наличие ограничений в обороте"),
    TYPE_OF_TRANSPORT("Вид транспорта"),
    TYPE_THINGS("Тип изделия");


    private final String label;

    LabelsConformity(String label) {
        this.label = label;
    }

    public String getlabel() {
        return label;
    }
}
